# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6de0ce06e7294bba828d1837daaed79219a64da2e5235119c7e6bbdc55ab37bd7d331a279a26db80e1c43302c07e2e5b6df5dd07019307ca767e04f25328ea92

test:
  secret_key_base: e38d49f42bc1b0f6964661879bcbe2c423118d03686cab6e0fbf59ec41e32ce27872877390296c5858d831041755bff0a423b9794a1e1179b3d689b62d6c1bc2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
